name: Testing Workflow
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "My first github action"
      - name: Print Goodbye
        run: echo "Goodbye"
